os: linux
language: cpp
matrix:
  include:
    - env: TEST=make
      language: c
      script: ./tests/make.sh

    - env: TEST=hadolint
      language: c
      services:
        - docker
      script: ./tests/hadolint.sh
branches:
  only:
  - master
notifications:
  email: false
